### ISSUE TITLE
[Bug]: `preventModdedMobSpawn` config doesn't function due to not using .equals()

### ISSUE THREAD

**Issue by CorgiTaco** [Mrbysco/CandyWorld#15]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

x

### Mod version

x

### Java version

x

### Issue Description

`preventModdedMobSpawn` config fails.

This line: https://github.com/Mrbysco/CandyWorld/blob/main/src/main/java/com/mrbysco/candyworld/events/EventHandler.java#L29

should use .equals(s2) since these are strings being compared. Strings should never be compared with `==` or `!=`

So it should be: 
```java
  if(livingEntity.getType().getRegistryName().getNamespace().equals(CandyWorld.MOD_ID)) {
```

**Comment by Mrbysco** [comment]
Apparently it slipped the cracks when I was going through the code
