### ISSUE TITLE
[Bug]: Candy World Biomes still spawn after setting config to 0

### ISSUE THREAD

**Issue by lSherozl** [Mrbysco/CandyWorld#16]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.28

### Mod version

Latest version

### Java version

Java 8 321

### Issue Description

Joined an existing world with config set to 0, did /locatebiome and still found the cotton candy biome spawning in overworld

**Comment by Mrbysco** [comment]
Have you restarted your game after changing the config?

**Comment by lSherozl** [comment]
I will do that and get back to you, I changed it at the main menu then joined a world

> Have you restarted your game after changing the config?

**Comment by lSherozl** [comment]
This issue can be closed, it wont work if you change the configs at the main menu, only works if you restart your game, on an another note, it would be cool to see the chocolate milk and other buckets have a purpose, you cant drink them or use them to make anything, thanks for the hard work
